export const defaultValues = {
  name: "",
  description: "",
  author: "",
  categoryId: "",
  subcategoryId: "",
  formatId: "",
  publicationYear: "",
  pageCount: "",
  weight: "",
  price: "",
  discount: "",
  stock: "",
  status: "",
  bookImage: null,
};
